[package]
name = "random_line"
version = "0.1.0"
authors = ["K1630549 <umar.marikar@kcl.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"